L_Art_du_Style/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # '' represents the "starts with" path
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('clothes/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),
    path('clothes/upload_top/', views.upload_top, name='upload_top'),
    path('clothes/upload_bottom/', views.upload_bottom, name='upload_bottom'),
    path('clothes/create_match/', views.create_match, name='create_match'),
    path('clothes/view_matches/', views.view_matches, name='view_matches'),
    path('clothes/<int:top_id>/delete_top/', views.delete_top, name='delete_top'),
    path('clothes/<int:bottom_id>/delete_buttom/', views.delete_bottom, name='delete_bottom'),
    path('matches/<int:match_id>/delete/', views.delete_match, name='delete_match'),
    path('clothes/<int:top_id>/edit_top/', views.edit_top, name='edit_top'),
    path('clothes/<int:bottom_id>/edit_buttom/', views.edit_bottom, name='edit_bottom'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Top(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='tops/')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.name} Top #{self.pk}"


class Bottom(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to='bottoms/')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.name} Bottom #{self.pk}"


class Match(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    top = models.ForeignKey(Top, on_delete=models.CASCADE, null=True)
    bottom = models.ForeignKey(Bottom, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Match #{self.pk}"

main_app/forms.py
from django import forms
from .models import Top, Bottom


class TopForm(forms.ModelForm):
    class Meta:
        model = Top
        fields = ['name', 'image']


class BottomForm(forms.ModelForm):
    class Meta:
        model = Bottom
        fields = ['name', 'image']

main_app/views.py
import os
import uuid
import boto3
import imghdr
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .forms import TopForm, BottomForm
from .models import Top, Bottom, Match


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


@login_required
def index(request):
    tops = Top.objects.filter(user=request.user)
    bottoms = Bottom.objects.filter(user=request.user)
    return render(request, 'clothes/index.html', {'tops': tops, 'bottoms': bottoms})


@login_required
def upload_top(request):
    if request.method == 'POST':
        form = TopForm(request.POST, request.FILES)
        if form.is_valid():
            photo_files = request.FILES.getlist('image')
            if len(photo_files) > 0:
                for photo_file in photo_files:
                    if photo_file:
                        if imghdr.what(photo_file) is not None:
                            s3 = boto3.client('s3')
                            key = f"tops/{uuid.uuid4().hex[:6]}{os.path.splitext(photo_file.name)[1]}"
                            try:
                                bucket = os.environ['S3_BUCKET']
                                s3.upload_fileobj(photo_file, bucket, key)
                                url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
                                new_top = Top(user=request.user, image=url)
                                new_top.save()
                            except Exception as e:
                                print('An error occurred uploading file to S3')
                                print(e)
                        else:
                            form.add_error(
                                'image', 'Please select an image file.')
                return redirect('index')
            else:
                form.add_error('image', 'Please select at least one file.')
    else:
        form = TopForm()
    return render(request, 'clothes/upload_top.html', {'form': form})


@login_required
def upload_bottom(request):
    if request.method == 'POST':
        form = BottomForm(request.POST, request.FILES)
        if form.is_valid():
            photo_files = request.FILES.getlist('image')
            if len(photo_files) > 0:
                for photo_file in photo_files:
                    if photo_file:
                        if imghdr.what(photo_file) is not None:
                            s3 = boto3.client('s3')
                            key = f"bottoms/{uuid.uuid4().hex[:6]}{os.path.splitext(photo_file.name)[1]}"
                            try:
                                bucket = os.environ['S3_BUCKET']
                                s3.upload_fileobj(photo_file, bucket, key)
                                url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
                                new_bottom = Bottom(
                                    user=request.user, image=url)
                                new_bottom.save()
                            except Exception as e:
                                print('An error occurred uploading file to S3')
                                print(e)
                        else:
                            form.add_error(
                                'image', 'Please select an image file.')
                return redirect('index')
            else:
                form.add_error('image', 'Please select at least one file.')
    else:
        form = BottomForm()
    return render(request, 'clothes/upload_bottom.html', {'form': form})


@login_required
def create_match(request):
    user_tops = Top.objects.filter(user=request.user)
    user_bottoms = Bottom.objects.filter(user=request.user)

    if user_tops.exists() and user_bottoms.exists():
        if request.method == 'POST':
            top_id = request.POST.get('top')
            bottom_id = request.POST.get('bottom')
            top = get_object_or_404(Top, id=top_id, user=request.user)
            bottom = get_object_or_404(Bottom, id=bottom_id, user=request.user)

            match = Match(user=request.user, top=top, bottom=bottom)
            match.save()

            return redirect('view_matches')
        else:
            tops = Top.objects.filter(user=request.user)
            bottoms = Bottom.objects.filter(user=request.user)
            return render(request, 'clothes/create_match.html', {'tops': tops, 'bottoms': bottoms})
    else:
        message = "Please upload at least one top and one bottom to create a match."
        return render(request, 'clothes/create_match.html', {'message': message})



@login_required
def view_matches(request, message=None):
    matches = Match.objects.filter(user=request.user)
    return render(request, 'clothes/view_matches.html', {'matches': matches, 'message': message})


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


@login_required
def delete_top(request, top_id):
    top = get_object_or_404(Top, id=top_id)
    if request.user == top.user:
        s3 = boto3.client('s3')
        key = top.image.url.split('/')[-1]
        bucket = os.environ['S3_BUCKET']
        try:
            s3.delete_object(Bucket=bucket, Key=key)
        except Exception as e:
            print('An error occurred deleting file from S3')
            print(e)
        top.delete()
    return redirect('index')


@login_required
def delete_bottom(request, bottom_id):
    bottom = get_object_or_404(Bottom, id=bottom_id)
    if request.user == bottom.user:
        s3 = boto3.client('s3')
        key = bottom.image.url.split('/')[-1]
        bucket = os.environ['S3_BUCKET']
        try:
            s3.delete_object(Bucket=bucket, Key=key)
        except Exception as e:
            print('An error occurred deleting file from S3')
            print(e)
        bottom.delete()
    return redirect('index')


@login_required
def delete_match(request, match_id):
    if request.method == 'POST':
        match = Match.objects.get(pk=match_id)
        match.delete()
        return redirect('view_matches')


@login_required
def edit_top(request, top_id):
    top = get_object_or_404(Top, id=top_id, user=request.user)
    if request.method == 'POST':
        form = TopForm(request.POST, request.FILES, instance=top)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = TopForm(instance=top)
    return render(request, 'clothes/edit_top.html', {'form': form, 'top': top})


@login_required
def edit_bottom(request, bottom_id):
    bottom = get_object_or_404(Bottom, id=bottom_id, user=request.user)
    if request.method == 'POST':
        form = BottomForm(request.POST, instance=bottom)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = BottomForm(instance=bottom)
    return render(request, 'clothes/edit_bottom.html', {'form': form, 'bottom': bottom})

main_app/templates/clothes/create_match.html
{% extends 'base.html' %} {% block content %}

<h1>Create a Match</h1>

{% if message %}
<p>{{ message }}</p>
{% else %}
<form method="post">
  {% csrf_token %}
  <div class="card-container">
    <div class="category">
      <h2 class="category-title">Select a Top:</h2>
    </div>
    
    {% for top in tops %}
    <label class="card-item card-top" onclick="selectTop(this)">
      <input
        type="radio"
        id="top{{ top.pk }}"
        name="top"
        value="{{ top.pk }}"
      />
      <img src="{{ top.image }}" alt="Top Image" width="200" />
      {{ top }}
    </label>
    {% endfor %}
  </div>

  <div class="card-container">
    <h2>Select a Bottom:</h2>

    {% for bottom in bottoms %}
    <label class="card-item card-bottom" onclick="selectBottom(this)">
      <input
        type="radio"
        id="bottom{{ bottom.pk }}"
        name="bottom"
        value="{{ bottom.pk }}"
      />
      <img src="{{ bottom.image }}" alt="Bottom Image" width="200" />
      {{ bottom }}
    </label>
    {% endfor %}
  </div>
  <p id="selected-top">No top selected.</p>
  <p id="selected-bottom">No bottom selected.</p>
  <input type="submit" value="Create Match" />
</form>
{% endif %}

<style>
  .card-container {
    display: flex;
    flex-wrap: wrap;
  }

  .card-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: 10px;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    cursor: pointer;
  }

  .selected {
    border-color: #ff0000; /* Update with your selected style */
  }

  /* Hover effect for top items */
  .card-top:hover {
    /* Add your hover styles for top items */
    background-color: #eaf2f8;
  }

  /* Hover effect for bottom items */
  .card-bottom:hover {
    /* Add your hover styles for bottom items */
    background-color: #f8f1ea;
  }
</style>

<script>
  function selectTop(element) {
    var selectedTop = document.getElementById("selected-top");
    selectedTop.innerText = "Selected: " + element.innerText;

    var topElements = document.getElementsByClassName("card-top");
    for (var i = 0; i < topElements.length; i++) {
      topElements[i].classList.remove("selected");
    }
    element.classList.add("selected");
  }

  function selectBottom(element) {
    var selectedBottom = document.getElementById("selected-bottom");
    selectedBottom.innerText = "Selected: " + element.innerText;

    var bottomElements = document.getElementsByClassName("card-bottom");
    for (var i = 0; i < bottomElements.length; i++) {
      bottomElements[i].classList.remove("selected");
    }
    element.classList.add("selected");
  }
</script>
{% endblock %}

main_app/templates/clothes/edit_bottom.html
{% extends 'base.html' %}
{% block content %}
  <h1>Edit Bottom</h1>
  <div>
      <img src="{{ bottom.image }}" alt="Bottom Image" width="200">
    </a>
  </div>
  <form method="post">
    {% csrf_token %}
    <div>
      <label for="id_name">Name:</label>
      <input type="text" id="id_name" name="name" value="{{ bottom.name }}">
    </div>
    <input type="submit" value="Save Changes">
  </form>
{% endblock %}

main_app/templates/clothes/edit_top.html
{% extends 'base.html' %}
{% block content %}
  <h1>Edit Top</h1>
  <div>
      <img src="{{ top.image }}" alt="Top Image" width="200">
    </a>
  </div>
  <form method="post">
    {% csrf_token %}
    <div>
      <label for="id_name">Name:</label>
      <input type="text" id="id_name" name="name" value="{{ top.name }}">
    </div>
    <input type="submit" value="Save Changes">
  </form>
{% endblock %}

main_app/templates/clothes/index.html
{% extends 'base.html' %} {% block content %}
<h1>Welcome to L'Art du Style</h1>
<p>Discover the perfect combination of top and bottom clothing items.</p>

<h1>My Closet</h1>

{% if tops %}
<div class="category">
  <h2>Tops:</h2>
</div>
<div class="card-container">
  {% for top in tops %}
  <div class="card-item card-top">
    <img src="{{ top.image }}" alt="Top Image" width="200" />
    <p>{{ top }}</p>
    <div>
      <a href="{% url 'edit_top' top.pk %}">Edit</a>
      <form
        action="{% url 'delete_top' top.pk %}"
        method="post"
        style="display: inline"
      >
        {% csrf_token %}
        <input type="submit" value="Delete" />
      </form>
    </div>
  </div>
  {% endfor %}
</div>
{% endif %} {% if bottoms %}
<div class="category">
  <h2>Bottoms:</h2>
</div>
<div class="card-container">
  {% for bottom in bottoms %}
  <div class="card-item card-bottom">
    <img src="{{ bottom.image }}" alt="Bottom Image" width="200" />
    <p>{{ bottom }}</p>
    <div>
      <a href="{% url 'edit_bottom' bottom.pk %}">Edit</a>
      <form
        action="{% url 'delete_bottom' bottom.pk %}"
        method="post"
        style="display: inline"
      >
        {% csrf_token %}
        <input type="submit" value="Delete" />
      </form>
    </div>
  </div>
  {% endfor %}
</div>
{% endif %}

<a href="{% url 'upload_top' %}">Upload Top</a>/
<a href="{% url 'upload_bottom' %}">Upload Bottom</a>/
<a href="{% url 'create_match' %}">Create Match</a>/
<a href="{% url 'view_matches' %}">View Matches</a>

<style>
  .card-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  .card-top {
    background-color: #f0f0f0;
  }

  .card-bottom {
    background-color: #eaf2f8;
  }

  .card-item {
    width: 200px;
    padding: 10px;
    margin-bottom: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    text-align: center;
  }

  .card-item img {
    max-width: 100%;
    height: auto;
  }

  .card-item p {
    margin-top: 10px;
  }

  .card-item div {
    margin-top: 20px;
  }

  .card-item div a,
  .card-item div form {
    margin-right: 10px;
  }

  .category {
    margin-bottom: 20px;
  }
</style>

{% endblock %}

main_app/templates/clothes/upload_bottom.html
{% extends 'base.html' %} {% block content %}
<h1>Upload Bottoms</h1>

{% if bottoms %}
<h2>Bottoms:</h2>
<div>
  {% for bottom in bottoms %}
  <div class="clothing-item">
    <img src="{{ bottom.image }}" alt="Bottom Image" width="200" />
    <p>{{ bottom }}</p>
  </div>
  {% endfor %}
</div>
{% endif %}

<form
  action="{% url 'upload_bottom' %}"
  enctype="multipart/form-data"
  method="POST"
  class="card-panel"
>
  {% csrf_token %}

  <label for="id_image">Image:</label>
  <input type="file" name="image" id="id_image" multiple />

  <button type="submit">Upload</button>
</form>

{% endblock %}

main_app/templates/clothes/upload_top.html
{% extends 'base.html' %} {% block content %}
<h1>Upload Top</h1>

{% if tops %}
<h2>Tops:</h2>
<div>
  {% for top in tops %}
  <div class="clothing-item">
    <img src="{{ top.image }}" alt="Top Image" width="200" />
    <p>{{ top }}</p>
  </div>
  {% endfor %}
</div>
{% endif %}

<form
  action="{% url 'upload_top' %}"
  enctype="multipart/form-data"
  method="POST"
  class="card-panel"
>
  {% csrf_token %}

  <label for="id_image">Image:</label>
  <input type="file" name="image" id="id_image" multiple />

  <button type="submit">Upload</button>
</form>
{% endblock %}

main_app/templates/clothes/view_matches.html
{% extends 'base.html' %} {% block content %}
<h1>View Matches</h1>

{% if matches %}
<div class="matches-container">
  {% for match in matches %}
  <div class="match-item">
    <div class="top-item">
      <img src="{{ match.top.image }}" alt="Top Image" width="200" />
      <p>{{ match.top }}</p>
    </div>
    <div class="bottom-item">
      <img src="{{ match.bottom.image }}" alt="Bottom Image" width="200" />
      <p>{{ match.bottom }}</p>
    </div>
    <form action="{% url 'delete_match' match.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Delete Match" />
    </form>
  </div>
  {% endfor %}
</div>
{% else %}
<p>No matches found.</p>
{% endif %}

<style>
  .matches-container {
    display: flex;
    flex-wrap: wrap;
  }

  .match-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: 10px;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  .top-item,
  .bottom-item {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .top-item img,
  .bottom-item img {
    width: 200px;
    height: auto;
  }

  .top-item p,
  .bottom-item p {
    margin-top: 10px;
  }

  .match-item form {
    margin-top: 10px;
  }
</style>
{% endblock %}